### PR TITLE
New changes to the script

### PR DESCRIPTION
**Pull request by sosaeio**
Fixes #2

### CODE REVIEW

**Review by stephenlauck — APPROVED** [review]

**Comment by stephenlauck** [comment]
@sosaeio  you'll need to rebase and merge. Let me know if you need to help to know how to rebase.

**Comment by sosaeio** [comment]
@stephenlauck In my current branch I am about to issue these commands
```
git rebase master 
git checkout master
git merge shaky
git push origin master
```

**Comment by stephenlauck** [comment]
> @stephenlauck In my current branch I am about to issue these commands
> 
> ```
> git rebase master 
> git checkout master
> git merge shaky
> git push origin master
> ```

No it should be:

```
git checkout master
git pull origin master
git checkout shaky
git rebase master
FIX ANY CONFLICTS
git add FIXED FILES
git rebase --continue
ONCE YOUR DONE FIXING CONFLICTS AND IT'S DONE REBASING
git push origin skaky -f
```

**Comment by sosaeio** [comment]
I resolved the conflict, not sure why it's still showing up. Kindly advice if merging will fix this.

**Review by stephenlauck — APPROVED** [review]

**Comment by stephenlauck** [comment]
This branch still needs to be rebased correctly.

**Pull request merged**
